export const actionIds = {
  REGISGER_USER: 'REGISGER_USER',
  RESEND_CONFIRM_CODE: 'RESEND_CONFIRM_CODE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_ERRORS: 'SET_ERRORS',
  SET_LOADING: 'SET_LOADING',
  REGISGER_RESULT: 'REGISGER_RESULT',
  SAVE_USERDATA: 'SAVE_USERDATA',
  LOGIN_RESULT: 'LOGIN_RESULT',
  GET_USERDATA: 'GET_USERDATA',
  GET_USER_LIST: 'GET_USER_LIST'
}

export const mutationIds = {
  REGISGER_USER: 'REGISGER_USER',
  RESEND_CONFIRM_CODE: 'RESEND_CONFIRM_CODE',
  LOGIN: 'LOGIN',
  SET_ERRORS: 'SET_ERRORS',
  SET_LOADING: 'SET_LOADING',
  REGISGER_RESULT: 'REGISGER_RESULT',
  SAVE_USERDATA: 'SAVE_USERDATA',
  LOGIN_RESULT: 'LOGIN_RESULT'
}
